version: '3'
services:
  web:
    platform: linux/x86_64
    build: ./docker/web
    depends_on:
      - db
    privileged: true
    # command: /sbin/init #systemctl有効にする場合
    ports:
       - 80:80
       - 9000:9000
    volumes:
      - ./src:/var/www/html
      - ./docker/web/httpd.conf:/etc/httpd/conf/httpd.conf

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: academy_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8080:80
    volumes: 
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
